### ISSUE TITLE
[Help]

### ISSUE THREAD

**Issue by jskvbinmv** [torehc/sinucha#1]
Hola, intento a usar tu sistema para un espacio de jovenes en Alemania pero nunca he usado Django y mis habilidades en python son bastante limitados. Tienes tal vez un documento que explica el setup en más detalle?

**Comment by torehc** [comment]
Hola, te recomiendo empezar por el tutorial de [Django Girls](https://tutorial.djangogirls.org/es/) que lo explica todo muy bien.
